In [1]:
import pandas as pd
import numpy as np
import nltk
import re
import string

from collections import Counter
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

In [2]:
df = pd.read_excel(r'C:\Users\tljubicic\OneDrive - A1 Group\Desktop\LinkedInJobs.xlsx')

In [3]:
df.head()

,Job Title,Company Name,City,Region,Workplace Type,Work Type,Experience,Company Size,Industry,Job Description,Job Link,Industry_cleaned,Company_Size_cleaned,Job_Title_cleaned,Job_Title_cleaned2
0,Power Bi Consultant,On The Chart,Amsterdam,North Holland,Hybrid,Full-time,Full-time,1-10 employees,1-10 employees,"""Vacature pdf: https://onthechart.nl/wp-conten...",/jobs/view/3434789835/?alternateChannel=search...,NaN,1-10 employees,Power Bi Consultant,Power Bi Consultant
1,Business Intelligence Consultant,2Foqus,Breda,North Brabant,Hybrid,Full-time,Full-time,11-50 employees,11-50 employees,"""Lijkt het jou tof om aan de slag te gaan met ...",/jobs/view/3452045317/?alternateChannel=search...,NaN,11-50 employees,Business Intelligence Consultant,Business Intelligence Consultant
2,Informatieanalyst,Vektis,Zeist,Utrecht,Hybrid,Full-time,Associate,51-200 employees,Information Services,"""De standaarden en referentieproducten die wij...",/jobs/view/3415867258/?alternateChannel=search...,Information Services,51-200 employees,Informatieanalyst,Informatieanalyst
3,"Principal Biostatistician, Single Sponsor, Hom...",Labcorp,Leiden,South Holland,On-site,Full-time,Mid-Senior level,"10,001+ employees",Hospitals and Health Care,"""Principal Biostatistician our sponsor-dedicat...",/jobs/view/3355948375/?alternateChannel=search...,Hospitals and Health Care,"10,001+ employees","Principal Biostatistician, Single Sponsor, Hom...","Principal Biostatistician, Single Sponsor, Hom..."
4,Business Intelligence Consultant,Codex Recruitment - Cloud Technology Recruitment,Netherlands,Netherlands,Remote,Full-time,Mid-Senior level,11-50 employees,Staffing and Recruiting,"""Are you a Microsoft Business Intelligence spe...",/jobs/view/3430353155/?alternateChannel=search...,Staffing and Recruiting,11-50 employees,Business Intelligence Consultant,Business Intelligence Consultant

In [4]:
# JOB TITLES CLEANING, STANDARDIZE MORE
# DESCRIPTION CLEANING, GET MOST COMMON WORDS, GET SALARIES

In [5]:
df['Job_Title_cleaned2'].unique()

array(['Power Bi Consultant', 'Business Intelligence Consultant',
       'Informatieanalyst',
       'Principal Biostatistician, Single Sponsor, Home Or Office Based Emea',
       'Quant Researcher', 'Data Analyst', 'Bi Consultant',
       'Data & Pricing Analyst', 'Consultant Business Intelligence',
       'Quantitative Researcher  Experience Metrics',
       'Sustainability Analyst', 'Production Planner',
       'Principal Biostatistician / Statistical Scientist  Global Bios',
       'Graduate Quant Analyst  Start September 2023',
       'Crm Marketeer Acquisitie',
       'Intelligence Analyst  Netherlands Remote',
       'Adobe Analytics Consultant', 'Vendor Marketeer',
       'Transport Planner', 'Planner Logistics Emea', 'Gl Accountant',
       'Dispute Analyst', 'Business Controller  Lokale Overheid',
       'It Traineeship', 'Informatie Analyst Data', 'Business Analyst',
       'It Traineeship Defensie', 'Crm Marketeer', 'Atlassian Consultant',
       'Planner Sourcing & Operations', 'Informatie Analyst',
       'Supply Chain Planner', 'Tax Accountant', 'Assistant Accountant',
       'Draaier, Cnc Frezer En/Of Lasser',
       'Teammanager Financiă«N & Administraties',
       'Hearing Support Administrator', 'Homebased Job  Dutch',
       'Business Developer', 'Technisch Bedrijfsanalyst',
       'Product Analyst', 'Bi Business Analyst',
       'Business Informatie Analyst Â€“ Lokale Overheid', 'Hr Analyst',
       'Consultant It Strategy',
       'Intern, Data Analysis Techinques & Tools En',
       'Fast Track Data & Analytics', nan,
       'Business Intelligence Consultant Â€“ Veel Vrijheid!',
       'Data & Rapportage Analyst', 'Experienced Quantitative Researcher',
       'Journey Analytics Consultant',
       'Principal Statistician Dmc  Emea Home Based', 'Data Engineer',
       'Quant Analyst', 'Informatie Analyst Bi  Public Transport',
       'Biostatistician 2  Global Bios', 'Proces En Informatieanalyst',
       'Bi Analyst', 'Informatieanalyst Succesfactors',
       'Business Intelligence Analyst',
       'Business Data & Pricing Analyst, Roelofarendsveen',
       'Market Insights Analyst', 'Data Analist Netcapaciteit Bij Stedin',
       'Analytics Consultant'], dtype=object)

In [6]:
df['Job Description'] = df['Job Description'].astype('str')

In [7]:
df['Job Description'] = df['Job Description'].apply(str.lower)

In [8]:
df['Job Description'] = df['Job Description'].replace({'power bi','powerbi'}, regex=True)

In [9]:
# DESCRIPTION CLEANING, PARSING

#nltk.download('punkt')
#nltk.download('stopwords')

STOP_WORDS = stopwords.words()

def cleaning(text):
    """
    Convert to lowercase.
    Rremove URL links, special characters and punctuation.
    Tokenize and remove stop words.
    """
    text = text.lower()
    text = re.sub('https?://\S+|www\.\S+', '', text)
    text = re.sub('<.*?>+', '', text)
    text = re.sub('[%s]' % re.escape(string.punctuation), '', text)
    text = re.sub('\n', '', text)
    text = re.sub('[’“”…]', '', text)

    # removing the stop-words
    text_tokens = word_tokenize(text)
    tokens_without_sw = [
        word for word in text_tokens if not word in STOP_WORDS]
    filtered_sentence = (" ").join(tokens_without_sw)
    text = filtered_sentence

    return text

In [10]:
word_counter = df['Job Description'].apply(cleaning)

In [11]:
word_count = Counter(" ".join(word_counter).split()).most_common()
word_freq = pd.DataFrame(word_count, columns = ['Word', 'Frequency'])
#print(word_freq)

In [12]:
# MOST COMMON TOOLS USED IN DATA ANALYSIS
# ONLY TOOLS BECAUSE SOME WORDS MAY BE IN DUTCH

tools = ['sql', 'excel', 'python', 'r', 'tableau', 'powerbi', 'sas', 'jupyter', 'looker', 'spark', 'aws', 'azure', 'hadoop',
        'alteryx', 'rapidminer', 'spss', 'dax', 'matlab', 'power bi']

In [13]:
most_common_tools = word_freq[word_freq['Word'].isin(tools)]

In [14]:
# TRY TO GET SALARIES
# GET EXPERIENCE NEEDED (..YEARS)

df['Years_exp'] = df['Job Description'].str.findall("\d.{1,4}year.|\d.{1,4}jaar")

In [15]:
df['liststring'] = [','.join(map(str, l)) for l in df['Years_exp']]

In [16]:
#df.to_csv(r'C:\Users\tljubicic\OneDrive - A1 Group\Desktop\LinkedInCleaned.csv')

In [17]:
#most_common_tools.to_csv(r'C:\Users\tljubicic\OneDrive - A1 Group\Desktop\common_words.csv')

In [18]:
df['Years_exp'] = df['Job Description'].str.findall("\d.{1,4}year.|\d.{1,4}jaar")

In [19]:
#pattern = "|".join(str(v) for v in tools)
pattern =  r"(?:^|\s+)(" + "|".join(str(v) for v in tools) + r")(?:\s+|$)"

df['Job_skills'] = df['Job Description'].str.findall(pattern)

In [20]:
for i in df['Job_skills']:
    i = list(dict.fromkeys(i))
    print(i)

['power bi', 'dax']
[]
[]
['sas']
['azure', 'powerbi']
['python']
['azure', 'sql']
[]
[]
[]
['python', 'aws', 'jupyter', 'sql']
['sql']
['powerbi', 'tableau', 'sql', 'python', 'r']
['azure']
['sql', 'python']
[]
['spss']
['excel']
['sql']
['azure']
[]
['python', 'hadoop']
[]
[]
['excel', 'powerbi']
['python', 'sql', 'powerbi']
['looker', 'dax']
[]
[]
[]
[]
['excel']
['sas']
['excel']
[]
[]
['sql', 'python', 'tableau']
['excel', 'sql']
['excel', 'power bi']
['sql', 'tableau', 'python']
[]
['power bi', 'azure', 'dax']
['sql']
[]
['sql']
['sql']
[]
['sql']
['sql', 'tableau']
['power bi']
[]
['sql']
[]
['sql', 'python']
['sql']
['tableau', 'sql']
['excel']
[]
[]
[]
[]
[]
[]
['powerbi', 'python']
[]
[]
['power bi', 'azure']
['azure']
['python', 'r', 'powerbi']
[]
['sql']
['powerbi']
[]
[]
[]
[]
['excel']
['tableau', 'r', 'alteryx']
['sql', 'python', 'powerbi', 'tableau']
[]
['excel', 'python']
['tableau', 'sql']
['spark', 'tableau']
['python', 'sql']
[]
[]
[]
[]
[]
[]
['python']
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
['excel', 'tableau']
['excel']
[]
[]
['sql']
[]
['azure', 'power bi', 'sql', 'powerbi', 'python']
[]
['excel']
['sql']
['powerbi']
[]
['azure', 'excel']
[]
[]
['python']
['tableau', 'python']
['sql', 'python']
[]
['power bi']
[]
[]
[]
[]
['python', 'excel']
[]
['sas']
['azure', 'power bi']
[]
['powerbi', 'r']
[]
[]
['powerbi', 'excel', 'power bi']
['azure']
['sql', 'python']
[]
[]
['sas', 'r', 'python']
[]
[]
['python']
[]
['sas', 'excel', 'powerbi']
[]
[]
['r']
[]
['sql', 'sas', 'azure']
['tableau', 'power bi', 'azure']
[]
['sas']
['sql']
[]
[]
[]
['sql']
['sql', 'python']
['powerbi', 'excel']
['python', 'sql']
['python', 'r']
['sql', 'power bi', 'azure', 'dax', 'python']
['tableau']
[]
[]
[]
[]
[]
['powerbi']
[]
[]
['python']
['powerbi', 'sql']
[]
['r']
['sql', 'azure']
[]
['sql', 'tableau']
[]
[]
['power bi']
['power bi']
[]
['power bi', 'python']
['tableau', 'excel']
['power bi', 'dax', 'sql']
['power bi']
['powerbi']
[]
[]
[]
['power bi', 'sql', 'python']
[]
['python', 'r']
['python', 'excel']
['powerbi', 'python', 'azure']
['python']
[]
['sas', 'excel']

In [21]:
def func(x):
    return list(dict.fromkeys(x))

In [22]:
df['Job_skills'] = df['Job_skills'].apply(lambda x:func(x))

In [23]:
#df.to_csv(r'C:\Users\tljubicic\OneDrive - A1 Group\Desktop\LinkedInCleaned2.csv')